Mon Jun 29 12:53:06 CDT 2015 : Apache Derby Network Server - 10.11.1.2 - (1629631) started and ready to accept connections on port 1527
----------------------------------------------------------------
Mon Jun 29 12:53:10 CDT 2015:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance a816c00e-014e-4073-7947-ffffab5f6baf 
on database directory C:\Users\Lia\Documents\GitHub\Tutorials\LearningDatabases\Employees with class loader sun.misc.Launcher$AppClassLoader@60e53b93 
Loaded from file:/C:/Program%20Files/Java/jdk1.8.0_45/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_45-b14
user.dir=C:\Program Files\Java\jdk1.8.0_45\db
os.name=Windows 8.1
os.arch=amd64
os.version=6.3
derby.system.home=C:\Users\Lia\Documents\GitHub\Tutorials\LearningDatabases
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Mon Jun 29 12:53:17 CDT 2015:
Shutting down instance a816c00e-014e-4073-7947-ffffab5f6baf on database directory C:\Users\Lia\Documents\GitHub\Tutorials\LearningDatabases\Employees with class loader sun.misc.Launcher$AppClassLoader@60e53b93 
Mon Jun 29 12:53:17 CDT 2015 Thread[DRDAConnThread_2,5,main] (DATABASE = Employees), (DRDAID = {2}), Database 'Employees' shutdown.
----------------------------------------------------------------
Mon Jun 29 12:54:28 CDT 2015:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance a65c80ac-014e-4073-7947-ffffab5f6baf 
on database directory C:\Users\Lia\Documents\GitHub\Tutorials\LearningDatabases\Employees with class loader sun.misc.Launcher$AppClassLoader@60e53b93 
Loaded from file:/C:/Program%20Files/Java/jdk1.8.0_45/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_45-b14
user.dir=C:\Program Files\Java\jdk1.8.0_45\db
os.name=Windows 8.1
os.arch=amd64
os.version=6.3
derby.system.home=C:\Users\Lia\Documents\GitHub\Tutorials\LearningDatabases
Database Class Loader started - derby.database.classpath=''
Mon Jun 29 13:58:50 CDT 2015 Thread[DRDAConnThread_2,5,main] (XID = 369), (SESSIONID = 4), (DATABASE = Employees), (DRDAID = {5}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR 08004: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR 08004: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Mon Jun 29 13:58:50 CDT 2015 Thread[DRDAConnThread_2,5,main] (DATABASE = Employees), (DRDAID = {5}), Connection authentication failure occurred.  Reason: Invalid authentication..
